### PR TITLE
Updated loader

### PR DESCRIPTION
**Pull request by stoudtlr**
these changes were tested while also using PR from @Helias 
https://github.com/azerothcore/mod-buff-command/pull/20

build completes without errors

tested buff command in-game as well and it works
image

### CODE REVIEW

**Review by Helias — APPROVED** [review]

**Comment by Helias** [comment]
Nice, I think we need to change clang version from 6 to "clang", so the last one I guess.

Anyways, when the pipeline will succeed I will merge the other PR, update this and merge also this (now for this the pipeline will fail I expect)

**Comment by stoudtlr** [comment]
i'm working on a bunch of pr's for modules that haven't been updated since the loader change a couple months ago. i have a list of 46 that give the "deprecated loader api" warning in cmake.  I hadn't thought about the yml file.  I'll start checking the clang version on these as well.

**Comment by Helias** [comment]
I can't update this PR, could you?

**Comment by stoudtlr** [comment]
merged your changes into this

**Comment by Helias** [comment]
build is failing

**Comment by Helias** [comment]
I integrated your commits here https://github.com/azerothcore/mod-buff-command/pull/24

**Pull request closed without merging**
